packages:
  # all packages in subdirs of components/
  - 'firm/**'
  - 'element-plus-lib/**'
  - 'element-library/**'
  - 'element-ui-lib/**'
  - 'element-ui-lib2/**'
  - 'rainbow-cli/**'
  - 'rainbow-css/**'
  - 'rainbow-js/**'
  - 'rainbow-ui/**'
  - 'rainbow-utils/**'
  - 'rainbow-view/**'
  - 'r-hooks/**'
  - 'v-hooks/**'
  
 


 